FROM ubuntu:18.04
MAINTAINER ngshya
COPY startup-r /
RUN chmod +x /startup-r
RUN echo "root:root" | chpasswd
RUN useradd -m -s /bin/bash user
RUN echo "user:user" | chpasswd
ENV TZ=Europe/Rome
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt update
RUN apt dist-upgrade -y
RUN apt -y install htop \
 nano \
 git \
 r-base \
 r-base-dev \
 gdebi-core \
 wget \
 openssh-server
RUN wget https://download2.rstudio.org/server/bionic/amd64/rstudio-server-1.2.1335-amd64.deb && \
 gdebi -n rstudio-server-1.2.1335-amd64.deb && \
 rm rstudio-server-1.2.1335-amd64.deb
RUN echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
RUN echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
ENTRYPOINT /startup-r
